
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.gg147.battleship;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.io.Reader;

public class App {
  //field to rep 2 players
  final TextPlayer player1, player2;

  //constructor to init the class
  public App(TextPlayer p1, TextPlayer p2) {
    this.player1 = p1;
    this.player2 = p2;
  }

  //creates the two player and call constructor
  //shared buffer, printstream
  public static void main(String[] args) throws IOException{
    Board<Character> b1 = new BattleShipBoard<Character>(10, 20, 'X');
    Board<Character> b2 = new BattleShipBoard<Character>(10, 20, 'X');

    BufferedReader in = new BufferedReader(new InputStreamReader(System.in));
    V1ShipFactory factory = new V1ShipFactory();
    
    TextPlayer p1 = new TextPlayer("A", b1, in, System.out, factory);
    TextPlayer p2 = new TextPlayer("B", b2, in, System.out, factory);

    
    App game = new App(p1, p2);
    game.doPlacementPhase();
  }

  public void doPlacementPhase() throws IOException{
    player1.doPlacementPhase();
    player2.doPlacementPhase();
  
  }
}
